# vim:set et sw=2 ts=2:
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: ircd-config
  files:
  - config/badwords.channel.conf
  - config/ircd.motd
  - config/unrealircd.conf
resources:
- resources.yml
